#!/usr/bin/env python3

import sys

from rqt_gui.main import Main
import argparse




def add_arguments(parser):
    group = parser.add_argument_group('Options for rqt_interactive_image_view plugin')
    group.add_argument(
        '--topic', 
        nargs='?', 
        help='The topic name to subscribe to')
    group.add_argument(
        '--hide-menu', '-m',
        help='Hide RViz menu bar in plugin',
        action='store_true')
    group.add_argument(
        '--display-config', '-d', metavar='FILE',
        type=argparse.FileType('r'),
        help='A display config file (.rviz) to load')
    group.add_argument(
        '--ogre-log', '-l',
        help='Enable the rqt_rviz_ogre(N).log file',
        action='store_true')

main = Main()
sys.exit(main.main(
    sys.argv,
    standalone='rqt_interactive_image_view/ImageView',
    plugin_argument_provider=add_arguments))
